# Generated by Django 2.2 on 2019-05-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0002_auto_20190502_2356'), ('blog', '0003_auto_20190503_1009')]

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ名')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='複数選択できます。controlキー（Macではcommandキー）を使ってください', related_name='posts', to='blog.Category', verbose_name='カテゴリ'),
        ),
    ]
