# Generated by Django 2.2 on 2019-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190502_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='複数選択できます。controlキー（Macではcommandキー）を使ってください', related_name='posts', to='blog.Category', verbose_name='カテゴリ'),
        ),
    ]
